name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:20.10.24-dind
        options: --privileged
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t shubhamhirpara/docker-react -f Dockerfile.dev .

      - name: Run tests
        run: docker run -e CI=true shubhamhirpara/docker-react npm run test

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET_KEY }}
          aws-region: us-east-1

      - name: Zip source bundle
        run: zip -r frontend.zip . -x ".git/*" ".github/*"

      - name: Upload to S3
        run: |
          aws s3 cp frontend.zip s3://elasticbeanstalk-us-east-1-349960126778/frontend/frontend.zip

      - name: Deploy to Elastic Beanstalk
        run: |
          aws elasticbeanstalk create-application-version --application-name frontend \
            --version-label $GITHUB_SHA \
            --source-bundle S3Bucket=elasticbeanstalk-us-east-1-349960126778,S3Key=frontend/frontend.zip
          aws elasticbeanstalk update-environment --environment-name Frontend-env \
            --version-label $GITHUB_SHA